Document: vscp-driver-l1-logger
Title: Debian vscp-driver-l1-logger Manual
Author: <insert document author here>
Abstract: This manual describes what vscp-driver-l1-logger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vscp-driver-l1-logger/vscp-driver-l1-logger.sgml.gz

Format: postscript
Files: /usr/share/doc/vscp-driver-l1-logger/vscp-driver-l1-logger.ps.gz

Format: text
Files: /usr/share/doc/vscp-driver-l1-logger/vscp-driver-l1-logger.text.gz

Format: HTML
Index: /usr/share/doc/vscp-driver-l1-logger/html/index.html
Files: /usr/share/doc/vscp-driver-l1-logger/html/*.html
